[package]
name = "runjs-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "runjs"
path = "src/main.rs"

[dependencies]
runjs-runtime = { path = "../runjs-runtime" }
clap.workspace = true
anyhow.workspace = true
tokio.workspace = true

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
